version: "3"

services:

  app:
    build:
      context: .
      dockerfile: app.Dockerfile
    container_name: belezanaweb-product-api
    restart: always
    expose:
      - 8080
    ports:
      - 8080:8080
#    environment:
#      SPRING_PROFILES_ACTIVE: "prod"
